### PR TITLE
Feature add point clusters

### LINKED ISSUE #11: Add clusters for data points
- [x] Move data source to a database
- [x] Cluster by Province/Territory

### PR DESCRIPTION
**Pull request by roikle**
Features added:
- Added functionality for clustering points
- Added ability to add data sources
- Added ability to add layers

fix #11

### CODE REVIEW

**Comment by Noznoc** [comment]
@roikle please pull and check if you agree with my style changes for the clusters. I would like to increase the thickness (font-weight) of the numbers in the cluster still, but was not sure how to do that.

**Comment by Noznoc** [comment]
Also, was there consideration of exponential radius size instead of threshold?

**Comment by Noznoc** [comment]
Looks better with interpolation

**Comment by roikle** [comment]
@Noznoc This branch should be ready to merge, assuming you're ok with the changes to the cluster text.

**Comment by Noznoc** [comment]
Great thanks @roikle I am going to do one final review and then will merge on Monday.

**Comment by Noznoc** [comment]
Looks good, can we just confirm this works in IE plz @roikle

**Pull request merged**
